[package]
name = "rust_to_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "sum"
crate-type = ["staticlib"]
path = "src/lib.rs"
